### ISSUE TITLE
Makefile:197: recipe for target '/usr/src/php/ext/json/json_parser.tab.c' failed

### ISSUE THREAD

**Issue by laurencefass** [bytepark/docker-php7-xdebug#2]
$docker build .

failed to build...

Makefile:197: recipe for target '/usr/src/php/ext/json/json_parser.tab.c' failed
make: *** [/usr/src/php/ext/json/json_parser.tab.c] Error 127
The command '/bin/sh -c docker-php-ext-install json' returned a non-zero code: 2

**Comment by fbatschi** [comment]
Fixed with https://github.com/bytepark/docker-php7-xdebug/commit/c0a2939fc35a630cc1a78ab6ba60e4583a3b808f
